### ISSUE TITLE
Add test that verifies multi-cluster behavior

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/controller-runtime#2]
- [ ] Get an ObjectKey with cluster + name
- [ ] Get an ObjectKey with cluster + namespace + name
- [ ] List all cluster-scoped things in 1 logical cluster vs. another (make sure they're distinct)
- [ ] List all namespace-scoped things in 1 logical cluster vs. another (make sure they're distinct)
- [ ] Create works
- [ ] Update works
- [ ] Patch works
- [ ] Delete works

**Comment by stevekuznetsov** [comment]
https://github.com/kcp-dev/kcp/pull/1341 verifies that the controllers function, and the controllers use the above bullets to do their job, so indirectly that PR closes this out :)
