### ISSUE TITLE
Matching controller-runtime & kcp

### ISSUE THREAD

**Issue by fgiloux** [kcp-dev/controller-runtime#20]
We need an easy way to match a controller-runtime version with a kcp release.
Looking at [go.mod](https://github.com/kcp-dev/controller-runtime/blob/feature-logical-clusters-1.23/go.mod#L10-L11) is cumbersome.
Ideally we would either have a branch or tag of kcp version of controller-runtime that matches a kcp release branch/tag.

**Comment by ncdc** [comment]
It's mostly about lining up kcp-dev/apimachinery and kcp-dev/logicalcluster. apimachinery is still a bit of a moving target (at times), but logicalcluster can just be `go get github.com/kcp-dev/logicalcluster/v2@latest`.
