### ISSUE TITLE
Update to Kubernetes 1.28

### ISSUE THREAD

**Issue by xrstf** [kcp-dev/controller-runtime#41]
https://github.com/kcp-dev/kcp/pull/3017 just got merged, so we should work on updating this fork to 1.28.

**Comment by embik** [comment]
/close

We are already on 1.29 now: https://github.com/kcp-dev/controller-runtime/blob/607a854c2cfe6d5f50ee294bcde6a54f13b7f3ea/go.mod#L26

So this is resolved.
